# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-16 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_permissions_on_tables_for_user'),
    ]

    operations = [
        migrations.RunSQL(
            "GRANT SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO reidi_user;",
            "REVOKE SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public FROM reidi_user;"
        )
    ]
