# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_create_model_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=255, verbose_name='recurso')),
                ('objectives', models.TextField(blank=True, null=True, verbose_name='objetivos')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='requerimientos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('date_from', models.DateTimeField(verbose_name='fecha desde')),
                ('date_until', models.DateTimeField(verbose_name='fecha hasta')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area', verbose_name='area')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Domain', verbose_name='dominio')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'db_table': 'applications',
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
