# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_create_model_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripci\xf3n')),
            ],
            options={
                'db_table': 'states',
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
    ]
