# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_create_model_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is_default'),
        ),
    ]
