# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_field_is_default_to_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Changes',
            new_name='Change',
        ),
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
        migrations.AddField(
            model_name='application',
            name='states',
            field=models.ManyToManyField(through='app.Change', to='app.State'),
        ),
    ]
