# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_model_changes_to_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='icon_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='icon_link'),
        ),
    ]
