# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_create_model_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='document_number'),
        ),
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType', verbose_name='document_type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nro. de tel\xe9fono'),
        ),
    ]
