# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_field_document_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='nro. de documento'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.DocumentType', verbose_name='tipo de documento'),
        ),
    ]
