# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_field_area_from_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='area',
            field=models.CharField(default='', max_length=255, verbose_name='area'),
            preserve_default=False,
        ),
    ]
